SSS.Web/Controllers/ConfigurationController.cs
using SSS.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Models;
using Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Resources;
using System.Web;
using System.Web.Mvc;

namespace SSS.Controllers
{
    public class ConfigurationController : BaseController
    {
        #region Profile Permissions

        public ActionResult Permissions()
        {
            var kronosContext = GetKronosContext();
            var sssContext = GetSSSContext();


            List<AllowedCompanyModel> kronosEntries = kronosContext.LABORLEVELENTRies.Where(l=>l.LABORLEVELDEFID == 1).Select(l => new AllowedCompanyModel { LaborLevelEntryId = l.LABORLEVELENTRYID, Name = l.DESCRIPTION }).Take(10).ToList();
            List<CompanyPermission> companyPermissions = sssContext.CompanyPermissions.ToList();
            CompanyPermission permission;
            foreach (AllowedCompanyModel item in kronosEntries)
            {
                permission = companyPermissions.Where(p => p.LaborLevelEntryId == item.LaborLevelEntryId).FirstOrDefault();
                if (permission!= null)
                {
                    item.Allowed = permission.Allowed;
                }
            }

            ViewData["CompanyList"] = kronosEntries;
            ViewData["ProfileList"] = kronosContext.LOGONPROFILEs.Select(m => new SSSListObject { Description = m.PROFILENM, Value = m.LOGONPROFILEID.ToString() }).OrderBy(p => p.Description).ToList();
            return View();
        }

        public ActionResult _Sections(int profileId)
        {
            var context = GetSSSContext();

            List<AppSection> secList = context.AppSections.OrderBy(s => s.Name).ToList();
            List<ProfilePermission> grantedList = context.ProfilePermissions.Where(m => m.LogonProfileId == profileId).ToList();
            List<PermissionModel> list = new List<PermissionModel>();
            int notGrantedId = 0;
            foreach (AppSection child in secList)
            {
                PermissionModel model = new PermissionModel { Name = child.Name, ProfileId = profileId, SectionId = child.Id };

                ProfilePermission granted = grantedList.Where(p => p.AppSectionId == child.Id && p.LogonProfileId == profileId).FirstOrDefault();
                if (granted != null)
                {
                    model.Id = granted.Id;
                    model.Checked = true;
                }
                else
                {
                    model.Id = --notGrantedId;
                    model.Checked = false;
                }

                list.Add(model);
            }

            return View(list);
        }

        public JsonResult SavePermissions(List<PermissionModel> permissions, List<int> companies)
        {
            var context = GetSSSContext();

            if (permissions != null)
            {
                foreach (PermissionModel child in permissions)
                {
                    if (child.Id > 0 && child.Checked == false)
                    {
                        ProfilePermission perm = context.ProfilePermissions.Where(p => p.Id == child.Id).FirstOrDefault();
                        context.ProfilePermissions.Remove(perm);
                    }
                    else
                    {
                        if (child.Checked)
                        {
                            context.ProfilePermissions.Add(new ProfilePermission { AppSectionId = child.SectionId, LogonProfileId = child.ProfileId });
                        }
                    }
                }
            }

            context.CompanyPermissions.RemoveRange(context.CompanyPermissions.ToList());
            if(companies !=null)
            {
                foreach (int item in companies)
                {
                    context.CompanyPermissions.Add(new CompanyPermission { Allowed = true, LaborLevelEntryId = item });
                }
                
            }

            context.SaveChanges();

            return Json(new { status = "success" });
        }

        #endregion

        #region Pay Codes

        public ActionResult PayCodes()
        {          
            return View();
        }

        public ActionResult _PayCodes(int payCodeAction)
        {
            var kronosContext = GetKronosContext();
            var sssContext = GetSSSContext();

            List<PayCodeConfiguration> sssPayCodeList = sssContext.PayCodeConfigurations.ToList();

            List<PayCodeConfigurationModel> list = kronosContext.PAYCODEs.Where(s => s.VISIBLE_TO_USER.HasValue && s.VISIBLE_TO_USER.Value == 1).OrderBy(s => s.NAME).Select(p => new PayCodeConfigurationModel { PayCodeId = p.PAYCODEID, PayCodeName = p.NAME }).ToList();

            PayCodeConfiguration sssPc = null;
            foreach (PayCodeConfigurationModel item in list)
            {
                sssPc = sssPayCodeList.Where(s => s.KronosId == item.PayCodeId).FirstOrDefault();

                if (sssPc != null)
                {
                    item.IsOvertime = sssPc.Overtime;
                    item.IsShow = sssPc.Show;
                    item.IsRegular = sssPc.Regular;
                    item.IsSendToSap = sssPc.SendToSap;

                    switch (payCodeAction)
                    {
                        case 0:
                            {
                                item.Show = sssPc.Show;
                                break;
                            }
                        case 1:
                            {
                                item.Show = sssPc.Regular;
                                break;
                            }
                        case 2:
                            {
                                item.Show = sssPc.Overtime;
                                break;
                            }
                        case 3:
                            {
                                item.Show = sssPc.RegularDefault;
                                break;
                            }
                        case 4:
                            {
                                item.Show = sssPc.SendToSap;
                                break;
                            }
                    }
                }
            }

            bool showRadio = false;
            if(payCodeAction == 3)
            {
                showRadio = true;
            }

            ViewData["ShowRadio"] = showRadio;

            if(payCodeAction == 4)
            {
                list = list.Where(l => l.IsShow == true || l.IsRegular == true || l.IsOvertime == true).ToList();
            }

            return View(list);
        }

        public JsonResult SavePayCodes(List<int> checkedList, List<int> uncheckedList, int payCodeAction)
        {
            if (checkedList != null)
            {
                foreach (int item in checkedList)
                {
                    ManageSssPayCode(item, true, payCodeAction);
                }
            }

            if (uncheckedList != null)
            {
                foreach (int item in uncheckedList)
                {
                    ManageSssPayCode(item, false, payCodeAction);
                }
            }

            return Json(new { status = "success" });
        }

        private void ManageSssPayCode(int item, bool chk, int payCodeAction)
        {
            var context = GetSSSContext();

            PayCodeConfiguration sssPc = null;
            sssPc = context.PayCodeConfigurations.Where(p => p.KronosId == item).FirstOrDefault();

            if (sssPc == null)
            {
                sssPc = new PayCodeConfiguration { KronosId = item };
                SetCorrespondingProppertybasedOnAction(sssPc, payCodeAction, chk);
                context.PayCodeConfigurations.Add(sssPc);
            }
            else
            {
                SetCorrespondingProppertybasedOnAction(sssPc, payCodeAction, chk);
            }

            context.SaveChanges();

        }

        private void SetCorrespondingProppertybasedOnAction(PayCodeConfiguration sssPc, int payCodeAction, bool chk)
        {
            switch (payCodeAction)
            {
                case 0:
                    {
                        sssPc.Show = chk;
                        break;
                    }
                case 1:
                    {
                        sssPc.Regular = chk;
                        break;
                    }
                case 2:
                    {
                        sssPc.Overtime = chk;
                        break;
                    }
                case 3:
                    {
                        sssPc.RegularDefault = chk;
                        break;
                    }
                case 4:
                    {
                        sssPc.SendToSap = chk;
                        break;
                    }
            }
        }
        #endregion

        #region PayRuleConfiguration

        public ActionResult PayRules()
        {
            var sssContext = GetSSSContext();
            var kronosContext = GetKronosContext();

            List<PAYRULEID> kronosPayRuleList = kronosContext.PAYRULEIDS.ToList();
            List<PayRuleConfiguration> ssssPayRuleList = sssContext.PayRuleConfigurations.ToList();

            List<PayRuleConfigurationModel> list = new List<PayRuleConfigurationModel>();

            foreach (PAYRULEID item in kronosPayRuleList)
            {
                list.Add(new PayRuleConfigurationModel { PayRuleId = item.PAYRULEID1, PayRuleName = item.NAME, Checked = ssssPayRuleList.Where(p => p.PayRuleId == item.PAYRULEID1).Count() > 0 ? true : false });
            }

            return View(list);
        }

        public JsonResult SavePayRules(List<int> checkedList)
        {
            var sssContext = GetSSSContext();

SSS.Web/Views/Configuration/PayCodes.cshtml
@using Resources
@using Models
@using System.Resources
@using SSS.Models
@{
    ViewBag.Title = Resource.PayCodes;
    Layout = "~/Views/Shared/_Layout.cshtml";

    ResourceManager rm = new ResourceManager(typeof(Resource));
}

<div id="PayCodeForm">
    <div class="col-md-12">
        <div class="col-md-12">
            <h4>@Resource.PayCodes</h4>
        </div>
        <div class="col-md-12">
            <div class="col-md-2">
                @(Html.Kendo().DropDownList().Name("ddlAction")
                                          .Items(i =>
                                          {
                                              i.Add().Text(Resource.DisplayInTimesheet).Value("0");
                                              i.Add().Text(Resource.RegularHoursPayCode).Value("1");
                                              i.Add().Text(Resource.OvertimeHoursPayCode).Value("2");
                                              i.Add().Text(Resource.DefaultRegularPayCode).Value("3");
                                              i.Add().Text(Resource.PayCodesForSapFile).Value("4");
                                          })
                                          .HtmlAttributes(new { @style = "width:80%" })
                                          .Events(ev => ev.Change("ActionChanged"))
                )
            </div>
            <div class="col-md-8">

            </div>
            <div class="col-md-2">
                @Html.Kendo().Button().Name("btnSavePayCodes").Content(Resource.Save).HtmlAttributes(new { @style = "margin-bottom:15px; width:100%" }).Events(ev => ev.Click("SavePayCodes")).Icon("tick")
            </div>
          
        </div>
        <div class="col-md-12">
            @Html.Label(Resource.SelectPayCodesForTimesheet, new { id = "lblPayCodeAction" })
        </div>
    </div>
    <hr class="searchhr" style="margin-bottom:10px" />
    <div id="divPayCodes"></div>
   
</div>
<script>

    function SavePayCodes()
    {
        ShowModal("fullModal");

        var checkedList = [];
        var uncheckedList = [];
        $('.paycodeitem:checked').each(function (i, item)
        {
            checkedList.push($(item).attr('paycodeid'));
        });
        $('.paycodeitem:not(:checked)').each(function (i, item)
        {
            uncheckedList.push($(item).attr('paycodeid'));
        });

        var payCodeAction = $('#ddlAction').data('kendoDropDownList').value()

        $.ajax({
            type: "Post",
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            url: '@Url.Action("SavePayCodes", "Configuration")',
            data: JSON.stringify({ checkedList, uncheckedList, payCodeAction}), // serializes the form's elements.
            success: function (result)
            {
                HideModal("fullModal");

                if (result.status == "success")
                {
                    NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
                else
                {
                    NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
            }
        });
    }

    function FilterPayCodes()
    {
        var searchVal = $('#txtFilterPayCodes').val().toLowerCase();

        $('.paycodeitem').each(function (i, item)
        {
            if ($(item).attr('paycodename').toLocaleLowerCase().includes(searchVal))
            {
                $(item).closest('div').show();
            }
            else
            {
                $(item).closest('div').hide();
            }
        });
    }

    function FilterPayCodesTextBoxKeyDown()
    {
        FilterPayCodes();
    }

    function ClearFilterpayCodesClick()
    {
        $('#txtFilterPayCodes').val('');
        FilterPayCodes();
    }

    function SelectAllClick()
    {
        $('.paycodeitem').prop("checked", true)
    }

    function UnselectAllClick()
    {
        $('.paycodeitem').prop("checked", false)
    }

    function ActionChanged()
    {
        ShowModal("fullModal");

        switch ($('#ddlAction').data('kendoDropDownList').value())
        {
            case "0":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectPayCodesForTimesheet")
                    break;
                }
            case "1":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectRegularPayCodes")
                    break;
                }
            case "2":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectOvertimePayCodes")
                    break;
                }
            case "3":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectPayCodeConsideredRegularConcept")
                    break;
                }
            case "4":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectPayCodesThatWillBeSentToSapFile")
                    break;
                }
        }

        LoadPayCodes();
    }

    function LoadPayCodes()
    {
        $("#divPayCodes").load('@Url.Action("_PayCodes", "Configuration")' + '?payCodeAction=' + $('#ddlAction').data('kendoDropDownList').value(), function ()
        {
            HideModal("fullModal");

            switch ($('#ddlAction').data('kendoDropDownList').value())
            {
                case "0":
                    {
                        $('[isregular="true"]').attr('disabled', 'disabled');
                        $('[isovertime="true"]').attr('disabled', 'disabled');
                        break;
                    }
                case "1":
                    {
                        $('[isovertime="true"]').attr('disabled', 'disabled');
                        break;
                    }
                case "2":
                    {
                        $('[isregular="true"]').attr('disabled', 'disabled');
                        break;
                    }               
             
            }
        });
    }

    $(document).ready(function ()
    {
        LoadPayCodes();
    });

</script>

SSS.Web/Views/Configuration/PayRules.cshtml
@using Resources
@using Models
@using System.Resources
@using SSS.Models
@{
    ViewBag.Title = Resource.PayCodes;
    Layout = "~/Views/Shared/_Layout.cshtml";

    ResourceManager rm = new ResourceManager(typeof(Resource));
}
@model  List<PayRuleConfigurationModel>
<div id="PayRuleForm">
    <div class="col-md-12">
        <div class="col-md-12">
            <h4>@Resource.PayRules</h4>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">

        </div>
        <div class="col-md-2">
            @Html.Kendo().Button().Name("btnSavePayRule").Content(Resource.Save).HtmlAttributes(new { @style = "margin-bottom:15px; width:100%" }).Events(ev => ev.Click("SavePayRules")).Icon("tick")
        </div>

    </div>
    <hr class="searchhr" style="margin-bottom:10px" />
    <div class="col-md-12">
        @foreach (PayRuleConfigurationModel item in Model)
        {
            <div class="col-md-2">@Html.Kendo().CheckBox().Name(item.PayRuleId.ToString()).Label(item.PayRuleName).Checked(item.Checked).HtmlAttributes(new { @class = "payruleitem", payrulename = item.PayRuleName, payruleid = item.PayRuleId })</div>
        }
    </div>
    <hr class="searchhr" style="margin-bottom:10px" />
    <div class="col-md-12">
        <div class="col-md-8" align="right">
            <span class="k-textbox k-space-right" style="width:250px">

                @Html.Kendo().TextBox().Name("txtFilterPayRules").HtmlAttributes(new { placeholder = Resource.Search, onkeyup = "FilterPayRuleTextBoxKeyDown()" })
                <a class="k-icon k-i-search">&nbsp;</a>
            </span>
            <span class="k-icon fa-eraser" onclick="ClearFilterPayRulesClick()" title="@Resource.ClearFilter" style="cursor:pointer">&nbsp;</span>
        </div>
        <div class="col-md-2">
            @(Html.Kendo().Button().Name("btnSelectAll").Content(Resource.CheckAll).HtmlAttributes(new { type = "button", style = "width:100%" }).Events(ev => ev.Click("SelectAllClick")).Icon("tick"))
        </div>
        <div class="col-md-2">
            @(Html.Kendo().Button().Name("btnUnSelectAll").Content(Resource.UncheckAll).HtmlAttributes(new { type = "button", style = "width:100%" }).Events(ev => ev.Click("UnselectAllClick")).Icon("cancel"))
        </div>
    </div>
</div>
<script>

    function SavePayRules()
    {
        ShowModal("fullModal");

        var checkedList = [];
        $('.payruleitem:checked').each(function (i, item)
        {
            checkedList.push($(item).attr('payruleid'));
        });
      
        $.ajax({
            type: "Post",
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            url: '@Url.Action("SavePayRules", "Configuration")',
            data: JSON.stringify({ checkedList}), // serializes the form's elements.
            success: function (result)
            {
                HideModal("fullModal");

                if (result.status == "success")
                {
                    NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
                else
                {
                    NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
            }
        });
    }

    function FilterPayCodes()
    {
        var searchVal = $('#txtFilterPayRules').val().toLowerCase();

        $('.payruleitem').each(function (i, item)
        {
            if ($(item).attr('payrulename').toLocaleLowerCase().includes(searchVal))
            {
                $(item).closest('div').show();
            }
            else
            {
                $(item).closest('div').hide();
            }
        });
    }

    function FilterPayRuleTextBoxKeyDown()
    {
        FilterPayCodes();
    }

    function ClearFilterPayRulesClick()
    {
        $('#txtFilterPayRules').val('');
        FilterPayCodes();
    }

    function SelectAllClick()
    {
        $('.payruleitem').prop("checked", true)
    }

    function UnselectAllClick()
    {
        $('.payruleitem').prop("checked", false)
    }

    function ActionChanged()
    {
        ShowModal("fullModal");

        switch ($('#ddlAction').data('kendoDropDownList').value())
        {
            case "0":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectPayCodesForTimesheet")
                    break;
                }
            case "1":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectRegularPayCodes")
                    break;
                }
            case "2":
                {
                    $('#lblPayCodeAction').html("@Resource.SelectOvertimePayCodes")
                    break;
                }
        }

        LoadPayCodes();
    }

    function LoadPayCodes()
    {
        $("#divPayCodes").load('@Url.Action("_PayCodes", "Configuration")' + '?payCodeAction=' + $('#ddlAction').data('kendoDropDownList').value(), function ()
        {
            HideModal("fullModal");
        });
    }

    $(document).ready(function ()
    {
        LoadPayCodes();
    });

</script>

SSS.Web/Views/Configuration/Permissions.cshtml
@using Resources
@using Models
@using System.Resources
@using SSS.Models
@{
    /**/

    ViewBag.Title = Resource.Permissions;
    Layout = "~/Views/Shared/_Layout.cshtml";

    ResourceManager rm = new ResourceManager(typeof(Resource));

    List<AllowedCompanyModel> companies = (List<AllowedCompanyModel>)ViewData["CompanyList"];
    if (companies == null)
    {
        companies = new List<AllowedCompanyModel>();
    }
}

<script>
    function GetModuleId()
    {
        return { moduleId: $('#ddlModules').data('kendoDropDownList').value() }
    }

    function SaveProfilePermissions()
    {
        ShowModal("fullModal");

        var permissions = [];
        $("#SectionsForm input.k-checkbox").each(function (e)
        {
            if ($(this).attr("changed") == 'true')
            {
                permissions.push({ Id: $(this).prop("id"), Checked: $(this).is(":checked"), SectionId: $(this).attr("sectionid"), ProfileId: $(this).attr("profileid")  });
            }
        });

        var companies = [];
        $("#AllowedCompaniesForm input.k-checkbox:checked").each(function (e)
        {
            companies.push($(this).attr("laborlevelentryid"));
        });

        $.ajax({
            type: "Post",
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            url: '@Url.Action("SavePermissions", "Configuration")',
            data: JSON.stringify({ permissions, companies }), // serializes the form's elements.
            success: function (result)
            {
                HideModal("fullModal");

                if (result.status == "success")
                {
                    NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
                else
                {
                    NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
            }
        });
    }

    function ProfileChanged()
    {
        LoadAppSections()
    }

    function ProfileDataBound()
    {
        LoadAppSections()
    }

    function LoadAppSections()
    {
        $("#divSections").load('@Url.Action("_Sections", "Configuration")' + '?profileId=' + $('#ddlProfiles').data('kendoDropDownList').value(), function ()
        {
            HideModal("fullModal");
        });
    }


</script>
<div style="margin:50px">
    <div id="AllowedCompaniesForm" class="col-md-6">
        <div class="col-md-12">
            <h4>@Resource.AllowedCompanies</h4>
        </div>
        <div class="col-md-12">
            <div class="col-md-10">
                <label>@Resource.SelectAllowedCompanies</label>
            </div>
            <div class="col-md-1">

            </div>
            <div class="col-md-1">

            </div>
        </div>

        <hr class="searchhr" />
        <div class="col-md-12">
            @foreach (AllowedCompanyModel item in companies)
            {
                <div class="col-md-4">
                    @Html.Kendo().CheckBox().Name("entryid_" + item.LaborLevelEntryId.ToString()).Label(item.Name).Checked(item.Allowed).HtmlAttributes(new { laborlevelentryid = item.LaborLevelEntryId })
                </div>
            }
        </div>
        <hr class="searchhr" />
    </div>
    <div id="PorfilePermissionsForm" class="col-md-6">
        <div class="col-md-12">
            <div class="col-md-12">
                <div class="col-md-10" style="padding:0">
                    <h4 style="margin:0">@Resource.ProfilePermissions</h4>
                </div>
                <div class="col-md-2">
                    @Html.Kendo().Button().Name("btnSaveProfilePermissions").Content(Resource.Save).HtmlAttributes(new { @style = "width:100%" }).Events(ev => ev.Click("SaveProfilePermissions")).Icon("tick")
                </div>
            </div>
            <div class="col-md-4">
                @(Html.Kendo().DropDownList()
                            .Name("ddlProfiles")
                            .BindTo((List<SSS.Models.SSSListObject>)ViewData["ProfileList"])
                            .DataTextField("Description")
                            .DataValueField("Value")
                            .ValuePrimitive(true)
                            .Filter(FilterType.Contains)
                            .Events(ev => ev.DataBound("ProfileDataBound").Change("ProfileChanged")))
            </div>
            <div class="col-md-3">
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-10">
                <label>@Resource.SelectPermissionsForProfile</label>
            </div>
            <div class="col-md-1">

            </div>
            <div class="col-md-1">

            </div>
        </div>

        <hr class="searchhr" style="margin-bottom:0" />
        <div id="divSections"></div>
    </div>
</div>

SSS.Web/Views/Configuration/_PayCodes.cshtml
@using Resources
@using SSS.Models
@using System.Resources
@model IEnumerable<PayCodeConfigurationModel>
@{ 
    bool showRadio = false;
    if(ViewData["ShowRadio"]!=null)
    {
        bool.TryParse(ViewData["ShowRadio"].ToString(), out showRadio);
    }


}

<script>

    function CheckBoxChanged(e)
    {
        $(e).attr('changed', 'true');
    }

</script>
<form id="PayCodesForm">
    <div class="col-md-12">
        @foreach (PayCodeConfigurationModel item in Model)
        {
            if (showRadio)
            {
                <div class="col-md-2">@Html.Kendo().RadioButton().Name(item.PayCodeId.ToString()).Label(item.PayCodeName).Checked(item.Show).HtmlAttributes(new { @class = "paycodeitem", @name="regulargaycode", paycodename = item.PayCodeName, paycodeid = item.PayCodeId })</div>
            }
            else
            {
                <div class="col-md-2">@Html.Kendo().CheckBox().Name(item.PayCodeId.ToString()).Label(item.PayCodeName).Checked(item.Show).HtmlAttributes(new { @class = "paycodeitem", paycodename = item.PayCodeName, paycodeid = item.PayCodeId, isregular = item.IsRegular.ToString().ToLower(), isshow = item.IsShow.ToString().ToLower(), isovertime = item.IsOvertime.ToString().ToLower(), issendtosap = item.IsSendToSap.ToString().ToLower() })</div>
            }

        }
    </div>
    <div class="col-md-12">
        <div class="col-md-8" align="right">
            <span class="k-textbox k-space-right" style="width:250px">
                @Html.Kendo().TextBox().Name("txtFilterPayCodes").HtmlAttributes(new { placeholder = Resource.Search, onkeyup = "FilterPayCodesTextBoxKeyDown()" })
                <a class="k-icon k-i-search">&nbsp;</a>
            </span>
            <span class="k-icon fa-eraser" onclick="ClearFilterpayCodesClick()" title="@Resource.ClearFilter" style="cursor:pointer">&nbsp;</span>
        </div>
        <div class="col-md-2">
            @if (!showRadio)
            {
                @(Html.Kendo().Button().Name("btnSelectAll").Content(Resource.CheckAll).HtmlAttributes(new { type = "button", style = "width:100%" }).Events(ev => ev.Click("SelectAllClick")).Icon("tick"))
            }
        </div>
        <div class="col-md-2">
            @if (!showRadio)
            {
                @(Html.Kendo().Button().Name("btnUnSelectAll").Content(Resource.UncheckAll).HtmlAttributes(new { type = "button", style = "width:100%" }).Events(ev => ev.Click("UnselectAllClick")).Icon("cancel"))
            }
        </div>
    </div>
</form>
<hr class="searchhr" style="margin-bottom:10px" />

SSS.Web/Views/Configuration/_Sections.cshtml
@using Resources
@using SSS.Models
@using System.Resources
@model IEnumerable<PermissionModel>
@{
    ResourceManager rm = new ResourceManager(typeof(Resource));
}
<script>

    function CheckBoxChanged(e)
    {
        $(e).attr('changed', 'true');
    }

</script>
<form id="SectionsForm">
    <div class="col-md-12">
        @foreach (var item in Model)
        {
            <div class="col-md-2">@Html.Kendo().CheckBox().Name(item.Id.ToString()).Label(" " + rm.GetString(item.Name)).Checked(item.Checked).HtmlAttributes(new { onchange="CheckBoxChanged(this)", sectionId = item.SectionId, profileId = item.ProfileId})</div>
        }
    </div>
</form>
<hr class="searchhr" />